### ISSUE TITLE
Release of code and pretrained weights?

### ISSUE THREAD

**Issue by HashmatShadab** [UCSC-VLAA/AdvXL#1]
Thanks for sharing your work!

Any plans when to release code and pretrained weights?

**Comment by zw615** [comment]
Hi thanks for the interest in our work!

we are working on the preparation of code and weights. They should be released soon.

**Comment by HashmatShadab** [comment]
That's great! Can we expect the release within a few weeks ?

**Comment by HashmatShadab** [comment]
Any update on this?

**Comment by HashmatShadab** [comment]
Any update on this??

**Comment by Ankowa** [comment]
Hi, any update on this?

**Comment by HashmatShadab** [comment]
Any plans on releasing the code and weights?

**Comment by HashmatShadab** [comment]
Dear Authors

Kindly provide an update on this issue

**Comment by zw615** [comment]
Hi @HashmatShadab @Ankowa , so sorry for the late reply! I got quite busy with some other things recently. The largest AdvXL weights and corresponding evaluation code are released. Let me know if there is any other questions.

**Comment by HashmatShadab** [comment]
Hi @zw615 , The link does not seem to work. Can you please check it?

**Comment by cihangxie** [comment]
@HashmatShadab It should be fixed now
